#-*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "WordPressVM" do |wp|
    wp.vm.box = "ubuntu/focal64"
    wp.vm.box_check_update = false
    wp.vm.hostname = "WordPressVM"
    wp.vm.provision "shell", path: "disco_wp.sh"
    wp.vm.provision "shell", path: "provisionwp.sh"
    wp.vm.network "private_network", ip: "192.168.2.1", nic_type: "virtio", virtualbox__intnet: "mynet"
    wp.vm.network "forwarded_port", guest: 80, host: 8080
    wp.vm.provider "virtualbox" do |vb|
      vb.name = "WordPressVM"
      vb.memory = 1024
      vb.cpus = 1
      create_disk = "extradiskMariaDB.vmdk"
      unless File.exist?(create_disk)
	        vb.customize ["createmedium", "disk", "--filename", "extradiskMariaDB.vmdk", "--format", "vmdk", "--size", 1024 * 10 ]
      end
      vb.customize ["storageattach", "WordPressVM" , "--storagectl", "SCSI", "--port", "2", "--device", "0", "--type", "hdd", "--medium", create_disk]
    end
  end	


  config.vm.define "ElasticSearch" do |elk|
    elk.vm.box = "ubuntu/focal64"
    elk.vm.box_check_update = false
    elk.vm.hostname = "ElasticSearchVM"
    elk.vm.provision "shell", path: "provisionelk.sh"
    elk.vm.provision "shell", path: "disco_elk.sh"
    elk.vm.network "private_network", ip: "192.168.2.2", nic_type: "virtio", virtualbox__intnet: "mynet"
    elk.vm.network "forwarded_port", guest: 9200, host: 9200
    elk.vm.network "forwarded_port", guest: 80, host: 8081
    elk.vm.provider "virtualbox" do |vb|
      vb.name = "ElasticSearchVM"
      vb.memory = 4096
      vb.cpus = 1
      create_disk = "extradiskELK.vmdk"
      unless File.exist?(create_disk)
          vb.customize ["createmedium", "disk", "--filename", "extradiskELK.vmdk", "--format", "vmdk", "--size", 1024 * 10 ]
      end
      vb.customize ["storageattach", "ElasticSearchVM" , "--storagectl", "SCSI", "--port", "2", "--device", "0", "--type", "hdd", "--medium", create_disk]
    end
  end
end
